title: The Croft House
author:
  name: Digital Freedom
  email: 'digitalfreedom.me@gmail.com'
metadata:
    description: 'The Croft House is a comfortable modernised holiday cottage on the Isle of Harris in the Outer Hebrides, Scotland.'

