home:
  alias: '/home'

pages:
  theme: crofthouse
  markdown_extra: false
  process:
    markdown: true
    twig: false
  expires: 604800

cache:
  enabled: true
  check:
    method: file
  driver: auto
  prefix: 'g'
  gzip: true

twig:
  cache: true
  debug: true
  auto_reload: true
  autoescape: false

assets:
  css_pipeline: true
  css_minify: true
  css_rewrite: true
  js_pipeline: true
  js_minify: true

debugger:
  enabled: false
  twig: true
  shutdown:
    close_connection: true
